apiVersion: 1

datasources:

  - name: Valkey-SO1-202112092

    type: redis-datasource

    access: proxy

    url: redis://valkey:6379

    isDefault: true

    editable: true

    jsonData:
      client: standalone
      poolSize: 5
      timeout: 10
      pingInterval: 0